using Mulse.Modules;

namespace Service.Execution;

public sealed class RuntimeMulseState
{
    public List<string> PluginDirectories { get; set; } = [];

    public List<ManagedModulePackageDefinition> ManagedPackages { get; set; } = [];

    public List<PipelineDefinition> Pipelines { get; set; } = [];

    public List<FlowOrchestrationCheckpoint> OrchestrationCheckpoints { get; set; } = [];

    public List<FlowRetryState> PendingRetries { get; set; } = [];

    /// <summary>
    /// Values that resolve <c>{{config:reference}}</c> and <c>{{secret:reference}}</c> placeholder
    /// tokens generated by the BizTalk importer (and usable by any flow, hand-authored or imported).
    /// Stored alongside the rest of the runtime state so it benefits from the same optional at-rest
    /// encryption via <see cref="IRuntimeStatePayloadProtector"/> - secrets are not treated specially
    /// in storage, only in how the UI chooses to display them (masked).
    /// </summary>
    public Dictionary<string, string> ConfigValues { get; set; } = new(StringComparer.OrdinalIgnoreCase);
}
